In [1]:
import numpy as np

#### numpy创建数组

In [2]:
t1 = np.array([1,2,3,])
print(t1)
print(type(t1))

t2 = np.array(range(10))
print(t2)

[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]


#### 最快的生成数组的方法

In [3]:
t3 = np.arange(4,10,2)
print(t3)
print(type(t3))

print(t3.dtype)

t4 = np.array(range(1,4),dtype=float)
print(t4)
print(t4.dtype)

[4 6 8]
<class 'numpy.ndarray'>
int32
[1. 2. 3.]
float64


#### 调整数据类型

In [4]:
t5 = np.array([1,1,0,1,0,0],dtype=bool)
print(t5)
print(t5.dtype)

t6 = t5.astype("int8")
print(t6)
print(t6.dtype)

[ True  True False  True False False]
bool
[1 1 0 1 0 0]
int8


#### numpy中的小数

In [5]:
import random
t7 = np.array([random.random() for i in range(10)])
print(t7)
print(t7.dtype)

t8 = np.round(t7,2)
print(t8)

[0.26059192 0.02632966 0.65324137 0.15704784 0.57648913 0.05655944
 0.94252484 0.84710891 0.31738384 0.76164447]
float64
[0.26 0.03 0.65 0.16 0.58 0.06 0.94 0.85 0.32 0.76]


#### 数组的形状

In [6]:
m1 = np.arange(12)
print("--a)")
print(m1.reshape((3,4)))

m2 = np.arange(24).reshape((2,3,4))
print("--b)")
print(m2)

m3 = m2.reshape((4,6))
print("--c)")
print(m3)

print("--d)")
print(m3.reshape((24,)))

# m3 = m2.reshape((m2.shape[0] * m2.shape[1],))
# print(m3)

print("--e)")
print(m2.flatten())

print("--f)")
print(m3 + 2)
print(m3 * 2)
print(m3 / 2)

print("--g)")
m4 = np.arange(100,124).reshape((4,6))
print(m4)
print(m4 + m3)
print(m4 * m3)

print("--h)")
m5 = np.arange(0,6)
print(m3 - m5)
m6 = np.arange(4).reshape((4,1))
print(m3 - m6)

--a)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--b)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--c)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
--d)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
--e)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
--f)
[[ 2  3  4  5  6  7]
 [ 8  9 10 11 12 13]
 [14 15 16 17 18 19]
 [20 21 22 23 24 25]]
[[ 0  2  4  6  8 10]
 [12 14 16 18 20 22]
 [24 26 28 30 32 34]
 [36 38 40 42 44 46]]
[[ 0.   0.5  1.   1.5  2.   2.5]
 [ 3.   3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8.   8.5]
 [ 9.   9.5 10.  10.5 11.  11.5]]
--g)
[[100 101 102 103 104 105]
 [106 107 108 109 110 111]
 [112 113 114 115 116 117]
 [118 119 120 121 122 123]]
[[100 102 104 106 108 110]
 [112 114 116 118 120 122]
 [124 126 128 130 132 134]
 [136 138 140 142 144 146]]
[[   0  101  204  309  416  525]
 [ 636  749  864  981 1100 1221]