# Exercise 2 Numpy

In [2]:
import numpy as np

In [3]:
x = np.zeros(10)
print(x)

3) Assume you are working on Jupyter Notebook
   How to you get documentation of numpy multiply fuction?

4) Create a 3 X 3 Matrix with values ranging from 0 to 8

In [6]:
arr = np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


5) Create a 3 X 3 X 3 array with random values 

In [8]:
arr2 = np.random.random((3,3,3))
print(arr2)

[[[0.16766299 0.59147542 0.16010117]
  [0.62406939 0.59298478 0.81996297]
  [0.59672063 0.34141181 0.02956167]]

 [[0.64320722 0.27450265 0.2879513 ]
  [0.04938694 0.30133356 0.90552306]
  [0.37315379 0.78322749 0.34071368]]

 [[0.09036115 0.07928236 0.19530203]
  [0.91132875 0.11556548 0.4872343 ]
  [0.02855677 0.70037818 0.44210931]]]


6) Create a 5 X 5 array with random values.  Find the minimum and maximum values.

In [19]:
arr3 = np.random.random((5,5))
print("Original Array:")
print(arr3)
print("Minimum and maximum values:")
print(arr3.min(),arr3.max())

Original Array:
[[0.9308151  0.99770007 0.44171273 0.18336957 0.55266911]
 [0.10402149 0.66163299 0.72919196 0.12276551 0.4953895 ]
 [0.04399902 0.52803317 0.06654164 0.81851453 0.55167547]
 [0.61797935 0.97144034 0.33892814 0.57497081 0.68542545]
 [0.148136   0.22189219 0.61012893 0.16035901 0.449919  ]]
Minimum and maximum values:
0.043999016811852254 0.9977000748984973


7) Create an array of 10 random values.  Rearrange the arrange in order.

In [20]:
arr4 = np.random.random(10)
print(np.sort(arr4))

[0.18184385 0.2604845  0.31363885 0.62152316 0.62306374 0.66990399
 0.71463069 0.87013486 0.90067582 0.94900376]


8) Create an array of 10 random values.  Get the sum and average value of the elements.

In [18]:
arr5 = np.random.random(10)
print("Original Array:")
print(arr5)

print("Sum of array:",np.sum(arr5))
print("Average of array:",np.average(arr5))

Original Array:
[0.47076109 0.96107599 0.86154447 0.90248338 0.12812451 0.05956647
 0.26294577 0.99080013 0.71041734 0.81641455]
Sum of array: 6.16413369851126
Average of array: 0.616413369851126
