In [60]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [61]:
data = pd.read_csv('banknotes.csv').values
data

array([['BN1', 214.8, 131.0, ..., 9.7, 141.0, 1],
       ['BN2', 214.6, 129.7, ..., 9.5, 141.7, 1],
       ['BN3', 214.8, 129.7, ..., 9.6, 142.2, 1],
       ...,
       ['BN198', 214.8, 130.3, ..., 11.1, 140.0, 0],
       ['BN199', 214.7, 130.7, ..., 11.2, 139.4, 0],
       ['BN200', 214.3, 129.9, ..., 11.5, 139.6, 0]], dtype=object)

In [62]:
features = data[:,1:7]
features

array([[214.8, 131.0, 131.1, 9.0, 9.7, 141.0],
       [214.6, 129.7, 129.7, 8.1, 9.5, 141.7],
       [214.8, 129.7, 129.7, 8.7, 9.6, 142.2],
       ...,
       [214.8, 130.3, 130.4, 10.6, 11.1, 140.0],
       [214.7, 130.7, 130.8, 11.2, 11.2, 139.4],
       [214.3, 129.9, 129.9, 10.2, 11.5, 139.6]], dtype=object)

In [63]:
labels = data[:,7]
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0], dtype=object)

In [64]:
x_train,x_test,y_train,y_test = train_test_split(features, labels, 
                                                 test_size=0.1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(180, 6)
(20, 6)
(180,)
(20,)


In [65]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

print(x_train)
print(x_test)

[[ 0.27927289  0.73151696  0.81391444 -0.24866999 -0.58246748  0.58212018]
 [ 0.27927289 -0.64007734 -0.65849359 -0.31732121 -2.07314254  1.28008277]
 [-0.24987574  0.4571981   1.05931578  0.43784225  1.77776804 -0.72655966]
 ...
 [-0.24987574 -0.36575848 -0.65849359  1.33030816 -0.08557579 -1.07554096]
 [ 1.86671877  0.73151696  0.32311176 -0.72922855 -0.45824456  0.49487486]
 [ 0.80842152  1.28015467  2.04092113  0.64379592  0.65976174 -0.1158424 ]]
[[ 0.5438472  -0.09143962 -0.16769091 -1.07248467  0.4113159   0.75661083]
 [ 0.27927289 -1.46303391 -1.88550029 -0.72922855 -0.58246748  1.45457342]
 [ 1.07299583 -1.18871505 -1.39469761 -1.34708957 -0.20979871  0.93110148]
 [ 0.5438472  -1.18871505 -0.65849359 -0.59192611 -0.45824456  0.14589357]
 [-0.51445006  0.4571981   0.5685131   0.91840081  0.53553882 -1.07554096]
 [ 2.13129309  1.82879239  1.30471712 -0.31732121 -0.7066904   0.84385615]
 [-0.24987574  0.18287924  0.81391444  0.36919103  1.5293222  -0.98829563]
 [ 0.80842152 -0.64

In [66]:
le = LabelEncoder()
le.fit(labels)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

print(y_train)
print(y_test)

[1 1 0 0 0 0 1 0 0 0 0 1 0 1 1 1 1 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 1
 0 0 1 1 1 1 0 1 1 1 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 0 0 1 1 0 0 1 1 1 1 1
 1 0 0 0 0 0 0 1 1 0 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 0 1 0 0 1 0 1 0 1 1 1 0
 0 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 0 0 0 1 0 0 1 0 1 1 0 1 0 1 1 0
 1 0 0 0 0 1 1 1 1 0 1 1 0 1 0 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0]
[1 1 1 1 0 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1]


In [67]:
x_train=np.asarray(x_train).astype('float32')
x_test=np.asarray(x_test).astype('float32')
y_train=np.asarray(y_train).astype('float32')
y_test=np.asarray(y_test).astype('float32')

In [68]:
y_train = tf.keras.utils.to_categorical(y_train,2)
y_test = tf.keras.utils.to_categorical(y_test,2)
print(y_train.shape)
print(y_test.shape)

(180, 2)
(20, 2)


In [69]:
# build model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(units=80,input_shape=(x_train.shape[1],), activation='sigmoid'))
model.add(tf.keras.layers.Dense(units=50,activation='sigmoid'))
model.add(tf.keras.layers.Dense(units=2, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

#run model
model.fit(x_train,y_train, epochs=200)

Epoch 1/200
6/6 [==============================] - 0s 666us/step - loss: 0.8994 - accuracy: 0.4778
Epoch 2/200
6/6 [==============================] - 0s 862us/step - loss: 0.7200 - accuracy: 0.4778
Epoch 3/200
6/6 [==============================] - 0s 837us/step - loss: 0.6672 - accuracy: 0.6333
Epoch 4/200
6/6 [==============================] - 0s 831us/step - loss: 0.6604 - accuracy: 0.5222
Epoch 5/200
6/6 [==============================] - 0s 832us/step - loss: 0.6472 - accuracy: 0.5222
Epoch 6/200
6/6 [==============================] - 0s 992us/step - loss: 0.6251 - accuracy: 0.6778
Epoch 7/200
6/6 [==============================] - 0s 998us/step - loss: 0.6026 - accuracy: 0.9111
Epoch 8/200
6/6 [==============================] - 0s 832us/step - loss: 0.5859 - accuracy: 0.9556
Epoch 9/200
6/6 [==============================] - 0s 1ms/step - loss: 0.5669 - accuracy: 0.9444
Epoch 10/200
6/6 [==============================] - 0s 1ms/step - loss: 0.5435 - accuracy: 0.9556
Epoch 11/200


6/6 [==============================] - 0s 997us/step - loss: 0.0180 - accuracy: 0.9944
Epoch 84/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0177 - accuracy: 0.9944
Epoch 85/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0177 - accuracy: 0.9944
Epoch 86/200
6/6 [==============================] - 0s 997us/step - loss: 0.0173 - accuracy: 0.9944
Epoch 87/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0171 - accuracy: 0.9944
Epoch 88/200
6/6 [==============================] - 0s 831us/step - loss: 0.0167 - accuracy: 0.9944
Epoch 89/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0164 - accuracy: 0.9944
Epoch 90/200
6/6 [==============================] - 0s 831us/step - loss: 0.0163 - accuracy: 0.9944
Epoch 91/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0161 - accuracy: 0.9944
Epoch 92/200
6/6 [==============================] - 0s 826us/step - loss: 0.0158 - accuracy: 0.9944
Epoch 93/200
6/6 [=====

6/6 [==============================] - 0s 993us/step - loss: 0.0074 - accuracy: 1.0000
Epoch 165/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0075 - accuracy: 1.0000
Epoch 166/200
6/6 [==============================] - 0s 665us/step - loss: 0.0073 - accuracy: 1.0000
Epoch 167/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0073 - accuracy: 1.0000
Epoch 168/200
6/6 [==============================] - 0s 665us/step - loss: 0.0072 - accuracy: 1.0000
Epoch 169/200
6/6 [==============================] - 0s 832us/step - loss: 0.0072 - accuracy: 1.0000
Epoch 170/200
6/6 [==============================] - 0s 831us/step - loss: 0.0071 - accuracy: 1.0000
Epoch 171/200
6/6 [==============================] - 0s 1ms/step - loss: 0.0072 - accuracy: 1.0000
Epoch 172/200
6/6 [==============================] - 0s 665us/step - loss: 0.0069 - accuracy: 1.0000
Epoch 173/200
6/6 [==============================] - 0s 997us/step - loss: 0.0069 - accuracy: 1.0000
Epoch 174/

In [75]:
# perform auto-evaluation
loss, accuracy = model.evaluate(x_test, y_test, verbose=1)
print(loss, accuracy)

# the same as following format
results = model.evaluate(x_test, y_test, verbose=1)
print('results = ', results, '\n')

1/1 [==============================] - 0s 2ms/step - loss: 3.2636e-04 - accuracy: 1.0000
0.000326355395372957 1.0
1/1 [==============================] - 0s 999us/step - loss: 3.2636e-04 - accuracy: 1.0000
results =  [0.000326355395372957, 1.0] 



In [78]:
# perform manual-evaluation
pred = model.predict(x_test)
for i in range(len(pred)):
    print('Actual:',y_test[i],'Predicted:',pred[i])

Actual: [0. 1.] Predicted: [2.9767252e-04 9.9970227e-01]
Actual: [0. 1.] Predicted: [4.2386113e-05 9.9995756e-01]
Actual: [0. 1.] Predicted: [4.9023234e-05 9.9995100e-01]
Actual: [0. 1.] Predicted: [4.9701805e-04 9.9950302e-01]
Actual: [1. 0.] Predicted: [9.9973112e-01 2.6883915e-04]
Actual: [0. 1.] Predicted: [0.00215723 0.9978428 ]
Actual: [1. 0.] Predicted: [9.9972564e-01 2.7431233e-04]
Actual: [0. 1.] Predicted: [5.8938935e-05 9.9994111e-01]
Actual: [0. 1.] Predicted: [3.9096783e-05 9.9996090e-01]
Actual: [0. 1.] Predicted: [4.6163084e-05 9.9995387e-01]
Actual: [0. 1.] Predicted: [3.7655547e-05 9.9996233e-01]
Actual: [1. 0.] Predicted: [9.9919361e-01 8.0641016e-04]
Actual: [0. 1.] Predicted: [1.5875802e-04 9.9984121e-01]
Actual: [1. 0.] Predicted: [9.9936563e-01 6.3439657e-04]
Actual: [0. 1.] Predicted: [8.197113e-05 9.999180e-01]
Actual: [1. 0.] Predicted: [9.9953294e-01 4.6708313e-04]
Actual: [1. 0.] Predicted: [9.9972636e-01 2.7363660e-04]
Actual: [0. 1.] Predicted: [2.0447961e-