In [14]:
import pandas as pd
import numpy as np
import string
import nltk
from nltk.corpus import stopwords

In [7]:
file = open('space_invaders.txt', encoding='utf-8')
doc = file.read()
file.close()

In [8]:
stop_words = set(stopwords.words('english'))

nltk.download('punkt')

porter = nltk.stem.PorterStemmer()
sentences = nltk.tokenize.sent_tokenize(doc)
print(sentences)

['Space Invaders is a fixed shooter in which the player controls a laser cannon by moving it horizontally across the bottom of the screen and firing at descending aliens.', 'The aim is to defeat five rows of eleven aliens—although some versions feature different numbers—that move horizontally back and forth across the screen as they advance toward the bottom of the screen.', "The player's laser cannon is partially protected by several stationary defense bunkers—the number also varies by version—that are gradually destroyed from the top and bottom by blasts from either the aliens or the player.", 'The player defeats an alien and earns points by shooting it with the laser cannon.', "As more aliens are defeated, the aliens' movement and the game's music both speed up.", 'Defeating all the aliens on-screen brings another wave that is more difficult, a loop which can continue endlessly.', 'A special "mystery ship" will occasionally move across the top of the screen and award bonus points if

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\甜甜子\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [11]:
# treat each sentence as a document
docs=[]
punc=str.maketrans('','',string.punctuation)
for ele in sentences:
    ele_nopunc = ele.translate(punc)
    words_stemmed = [porter.stem(w) for w in ele_nopunc.lower().split()]
    docs += [' '.join(words_stemmed)]

print(docs)

['space invad is a fix shooter in which the player control a laser cannon by move it horizont across the bottom of the screen and fire at descend alien', 'the aim is to defeat five row of eleven aliens—although some version featur differ numbers—that move horizont back and forth across the screen as they advanc toward the bottom of the screen', 'the player laser cannon is partial protect by sever stationari defens bunkers—th number also vari by version—that are gradual destroy from the top and bottom by blast from either the alien or the player', 'the player defeat an alien and earn point by shoot it with the laser cannon', 'as more alien are defeat the alien movement and the game music both speed up', 'defeat all the alien onscreen bring anoth wave that is more difficult a loop which can continu endlessli', 'a special mysteri ship will occasion move across the top of the screen and award bonu point if destroy', 'the alien attempt to destroy the player cannon by fire at it while they a

In [12]:
for i in range(0,len(docs)):
    print('doc' + str(i) + '=',docs[i])

doc0= space invad is a fix shooter in which the player control a laser cannon by move it horizont across the bottom of the screen and fire at descend alien
doc1= the aim is to defeat five row of eleven aliens—although some version featur differ numbers—that move horizont back and forth across the screen as they advanc toward the bottom of the screen
doc2= the player laser cannon is partial protect by sever stationari defens bunkers—th number also vari by version—that are gradual destroy from the top and bottom by blast from either the alien or the player
doc3= the player defeat an alien and earn point by shoot it with the laser cannon
doc4= as more alien are defeat the alien movement and the game music both speed up
doc5= defeat all the alien onscreen bring anoth wave that is more difficult a loop which can continu endlessli
doc6= a special mysteri ship will occasion move across the top of the screen and award bonu point if destroy
doc7= the alien attempt to destroy the player cannon b

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vec = TfidfVectorizer(analyzer='word',stop_words=stop_words)
tfidf_wm = tfidf_vec.fit_transform(docs).toarray()
print(tfidf_wm)

#生成一个矩阵，每个doc里面如果出现了该term就会有数值，没出现的数值就是0

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
df_index = ['doc'+str(i) for i in range(len(docs))]
print(df_index)
#列出所有doc，成为接下来要组建的dataframe的行名

['doc0', 'doc1', 'doc2', 'doc3', 'doc4', 'doc5', 'doc6', 'doc7', 'doc8', 'doc9', 'doc10', 'doc11', 'doc12', 'doc13', 'doc14', 'doc15', 'doc16', 'doc17', 'doc18', 'doc19', 'doc20', 'doc21', 'doc22', 'doc23', 'doc24', 'doc25', 'doc26', 'doc27', 'doc28', 'doc29', 'doc30', 'doc31', 'doc32', 'doc33', 'doc34', 'doc35', 'doc36', 'doc37', 'doc38', 'doc39', 'doc40', 'doc41', 'doc42', 'doc43', 'doc44', 'doc45', 'doc46', 'doc47', 'doc48', 'doc49', 'doc50', 'doc51']


In [20]:
df_columns = tfidf_vec.get_feature_names()
print(df_columns)
#列出所有unique的term,成为接下来要组建的dataframe的列名

['100yen', '1972', '1974', '1975', '1978', '1979', '8080', 'abil', 'abl', 'achiev', 'across', 'actual', 'adapt', 'add', 'addit', 'adopt', 'advanc', 'aim', 'alien', 'aliens', 'allow', 'also', 'alter', 'although', 'analog', 'anim', 'anoth', 'appear', 'approach', 'ar', 'arcad', 'artist', 'artwork', 'atari', 'attack', 'attempt', 'attribut', 'award', 'back', 'backdrop', 'background', 'ball', 'bank', 'barrel', 'barriersin', 'base', 'bass', 'battleship', 'becaus', 'behind', 'bitmap', 'blackandwhit', 'blast', 'board', 'bolt', 'bonu', 'bottom', 'bounc', 'breakout', 'bring', 'bunkers', 'cabinet', 'cannon', 'caus', 'cellophan', 'central', 'certain', 'challeng', 'chang', 'charact', 'children', 'chip', 'circuit', 'circuitri', 'circul', 'cite', 'clau', 'cocktail', 'cocktailt', 'coin', 'color', 'combat', 'combin', 'come', 'compens', 'complet', 'complex', 'concept', 'concert', 'consid', 'continu', 'control', 'could', 'cover', 'cpu', 'crab', 'creat', 'crt', 'custom', 'cutout', 'day', 'decid', 'declar',

In [24]:
tfidf_df = pd.DataFrame(data=tfidf_wm,index=df_index,columns=df_columns)
tfidf_df

#构建dataframe

100yen      1972      1974      1975      1978      1979      8080  \
doc0   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc1   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc2   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc3   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc4   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc5   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc6   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc7   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc8   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc9   0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc10  0.000000  0.233159  0.000000  0.000000  0.000000  0.000000  0.000000   
doc11  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc12  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc13  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc14  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc15  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc16  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc17  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc18  0.000000  0.000000  0.288778  0.000000  0.000000  0.000000  0.000000   
doc19  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc20  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc21  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc22  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc23  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc24  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.176469   
doc25  0.000000  0.000000  0.000000  0.206021  0.000000  0.000000  0.000000   
doc26  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc27  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.263313   
doc28  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc29  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc30  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc31  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc32  0.000000  0.000000  0.000000  0.000000  0.215087  0.000000  0.000000   
doc33  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc34  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc35  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc36  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc37  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc38  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc39  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc40  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc41  0.318376  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc42  0.296169  0.000000  0.000000  0.000000  0.296169  0.327185  0.000000   
doc43  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc44  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc45  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc46  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc47  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc48  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
doc49  0.000000  0.000000  0.000000  0.000000  0.000000  0.

In [29]:
# axis=1代表跨列，按行运算，axis=0代表跨行，按列运算
tfidf_sum_by_docs = np.sum(tfidf_df, axis=1) #此处将每个doc的数值分别求和
nwords_by_docs = np.sum(tfidf_df != 0, axis=1) #此处确认每个doc中有几个term
print(tfidf_sum_by_docs)
print(nwords_by_docs)

doc0     3.912255
doc1     4.414140
doc2     4.519584
doc3     2.781502
doc4     2.376074
doc5     3.123966
doc6     3.430478
doc7     2.952512
doc8     3.908374
doc9     3.727199
doc10    4.821202
doc11    2.932863
doc12    3.536538
doc13    2.800219
doc14    3.561863
doc15    2.917672
doc16    3.413221
doc17    2.799709
doc18    3.834832
doc19    3.574759
doc20    2.171319
doc21    3.554562
doc22    4.463970
doc23    2.803102
doc24    4.816107
doc25    4.414233
doc26    4.149037
doc27    3.831057
doc28    5.005198
doc29    3.770698
doc30    3.565317
doc31    3.138539
doc32    4.040074
doc33    1.655060
doc34    1.000000
doc35    2.646406
doc36    4.508764
doc37    4.715729
doc38    2.615499
doc39    4.402610
doc40    3.408534
doc41    3.241754
doc42    3.291540
doc43    3.595558
doc44    3.392349
doc45    3.591621
doc46    4.249475
doc47    3.304447
doc48    6.111494
doc49    4.171724
doc50    2.772986
doc51    3.793651
dtype: float64
doc0     16
doc1     20
doc2     21
doc3      8
d

In [30]:
nwords_by_docs = nwords_by_docs.sum(axis=0)/len(nwords_by_docs)
series = tfidf_sum_by_docs / nwords_by_docs
print(nwords_by_docs)
print(series)

14.365384615384615
doc0     0.272339
doc1     0.307276
doc2     0.314616
doc3     0.193625
doc4     0.165403
doc5     0.217465
doc6     0.238802
doc7     0.205530
doc8     0.272069
doc9     0.259457
doc10    0.335612
doc11    0.204162
doc12    0.246185
doc13    0.194928
doc14    0.247948
doc15    0.203104
doc16    0.237600
doc17    0.194893
doc18    0.266949
doc19    0.248845
doc20    0.151149
doc21    0.247439
doc22    0.310745
doc23    0.195129
doc24    0.335258
doc25    0.307283
doc26    0.288822
doc27    0.266687
doc28    0.348421
doc29    0.262485
doc30    0.248188
doc31    0.218479
doc32    0.281237
doc33    0.115212
doc34    0.069612
doc35    0.184221
doc36    0.313863
doc37    0.328270
doc38    0.182070
doc39    0.306474
doc40    0.237274
doc41    0.225664
doc42    0.229130
doc43    0.250293
doc44    0.236147
doc45    0.250019
doc46    0.295814
doc47    0.230028
doc48    0.425432
doc49    0.290401
doc50    0.193032
doc51    0.264083
dtype: float64


In [33]:
#将series排序，按照降序出现，便于我们选择前十个doc
sorted_series = series.sort_values(ascending=False)
top_series = sorted_series.head(10)

print("\n")

# remove the prefix 'doc' from indexes such as
# [doc10, doc24, doc11, ..., doc22]
num_only = [int(x[3:]) for x in top_series.index]
print(num_only)

for i in sorted(num_only):
    print(sentences[i] + "\n")



[48, 28, 10, 24, 37, 2, 36, 22, 25, 1]
The aim is to defeat five rows of eleven aliens—although some versions feature different numbers—that move horizontally back and forth across the screen as they advance toward the bottom of the screen.

The player's laser cannon is partially protected by several stationary defense bunkers—the number also varies by version—that are gradually destroyed from the top and bottom by blasts from either the aliens or the player.

The game's inspiration is reported to have come from varying sources, including an adaptation of the mechanical game Space Monsters released by Taito in 1972, and a dream about Japanese school children who are waiting for Santa Claus when they are attacked by invading aliens.

Because microcomputers in Japan were not powerful enough at the time to perform the complex tasks involved in designing and programming Space Invaders, Nishikado had to design his own custom hardware and development tools for the game.

The game uses an I